web/prisoner/game/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^first_prisoner$', views.first_prisoner, name='first_prisoner'),
    url(r'^help_page', views.help_page, name='help_page'),
    url(r'^second_prisoner$', views.second_prisoner, name='second_prisoner'),
    url(r'^results$', views.results, name='results'),
    url(r'^invalid_code$', views.results, name='invalid_code'),
)

web/prisoner/prisoner/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('game.urls', namespace="game")),
    url(r'^admin/', include(admin.site.urls)),
)

web/prisoner/game/models.py
from django.db import models


# Create your models here.
class Prisoner(models.Model):
    name = models.CharField(max_length=40, blank=False, help_text="This is the prisoner's name. Enter your name :)")
    strategy = models.CharField(max_length=1500, blank=False, help_text="This is the prisoner's strategy. Write it in Python.")
    years = models.IntegerField(default=0)

    def __str__(self):
        return '\nname: {}\nstrategy: {}\nyears: {!r}'.format(self.name, self.strategy, self.years)

web/prisoner/game/views.py
from django.shortcuts import render
from .models import Prisoner
from .game_engine.prisoner_DAL import save_prisoner, get_prisoner, delete_players_from_db
from .game_engine.game import play


def process_prisoner(request):
    prisoner = Prisoner(name=request.POST['name'], strategy=request.POST['strategy'])
    print(repr(prisoner))
    save_prisoner(prisoner)


def index(request):
    context = {'title': "Welcome to the Prisoner's Dilemma..."}
    return render(request, 'game/index.html', context)


def first_prisoner(request):

    context = {'title': "Welcome to the Prisoner's Dilemma...", 'prisoner_number': "1", "dest_page": "second_prisoner"}
    return render(request, 'game/prisoner.html', context)


def second_prisoner(request):
    process_prisoner(request)

    context = {'title': "Welcome to the Prisoner's Dilemma...", 'prisoner_number': "2", "dest_page": "results"}
    return render(request, 'game/prisoner.html', context)


def get_results_into_context():
    first_prisoner_object = get_prisoner(0)
    second_prisoner_object = get_prisoner(1)

    context = {}
    if first_prisoner_object.years != second_prisoner_object.years:
        context = {
            'winner':   first_prisoner_object if first_prisoner_object.years < second_prisoner_object.years else second_prisoner_object,
            'loser':    first_prisoner_object if first_prisoner_object.years > second_prisoner_object.years else second_prisoner_object}
    else:
        context = {
            'winner':   first_prisoner_object,
            'loser':    second_prisoner_object,
            'tie':      True}
    return context


def results(request):
    process_prisoner(request)

    try:
        play()
    except:
        delete_players_from_db()
        raise

    context = get_results_into_context()

    delete_players_from_db()

    return render(request, 'game/results.html', context)


def help_page(request):
    context = {}
    return render(request, 'game/help_page.html', context)

web/prisoner/game/templates/game/help_page.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'prisoner/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'prisoner/component.css' %}" />

<div id="headerwrapper">
    <div id="header">
        <h1>Help</h1>
        <div id="logo"></div>
    </div>
</div>
<div id="help" class="dark-matter">

        <button class="btn btn-4 btn-4b icon-arrow-left" onclick="window.location.href='{% url 'game:index' %}'">
            Back to main menu...
        </button>
        <p>
            <h1>What is the prisoner's dilemma?</h1>
<mark>The prisoner's dilemma</mark> is a canonical example of a game analyzed in game theory that shows why two purely "rational" individuals might not cooperate, even if it appears that it is in their best interests to do so. It was originally framed by Merrill Flood and Melvin Dresher working at RAND in 1950. Albert W. Tucker formalized the game with prison sentence rewards and gave it the name "prisoner's dilemma" (Poundstone, 1992), presenting it as follows:<br><br>
            <span>
                Two members of a criminal gang are arrested and imprisoned. Each prisoner is in solitary confinement with no means of speaking to or exchanging messages with the other. The police admit they don't have enough evidence to convict the pair on the principal charge. They plan to sentence both to a year in prison on a lesser charge. Simultaneously, the police offer each prisoner a Faustian bargain. Each prisoner is given the opportunity either to betray the other, by testifying that the other committed the crime, or to cooperate with the other by remaining silent. Here's how it goes:<br>
                <ul>
                    <li>If A and B each betray the other, each of them serves 2 years in prison.</li>
                    <li>If A betrays B but B remains silent, A will be set free and B will serve 3 years in prison (and vice versa)</li>
                    <li>If A and B both remain silent, both of them will only serve 1 year in prison (on the lesser charge)</li>
                </ul>
                <br>
            </span>
It is implied that the prisoners will have no opportunity to reward or punish their partner other than the prison sentences they get, and that their decision will not affect their reputation in the future. Because betraying a partner offers a greater reward than cooperating with them, all purely rational self-interested prisoners would betray the other, and so the only possible outcome for two purely rational prisoners is for them to betray each other. The interesting part of this result is that pursuing individual reward logically leads both of the prisoners to betray, when they would get a better reward if they both cooperated. In reality, humans display a systematic bias towards cooperative behavior in this and similar games, much more so than predicted by simple models of "rational" self-interested action. A model based on a different kind of rationality, where people forecast how the game would be played if they formed coalitions and then they maximize their forecasts, has been shown to make better predictions of the rate of cooperation in this and similar games given only the payoffs of the game.<br><br>
<b>There is also an extended "iterated" version of the game, where the classic game is played over and over between the same prisoners, and consequently, both prisoners continuously have an opportunity to penalize the other for previous decisions. If the number of times the game will be played is known to the players, then (by backward induction) two classically rational players will betray each other repeatedly, for the same reasons as the single shot variant. In an infinite or unknown length game there is no fixed optimum strategy, and Prisoner's Dilemma tournaments have been held to compete and test algorithms.</b><br><br>
The prisoner's dilemma game can be used as a model for many real world situations involving cooperative behaviour. In casual usage, the label "prisoner's dilemma" may be applied to situations not strictly matching the formal criteria of the classic or iterative games: for instance, those in which two entities could gain important benefits from cooperating or suffer from the failure to do so, but find it merely difficult or expensive, not necessarily impossible, to coordinate their activities to achieve cooperation.<br><br>
        </p>
        <p>
            <h1>How to play?</h1>
            In order to play, you need to enter your prisoner's strategies in python. The game will be played X times (the iterated version of the game). <br>
            Keeping quiet is <i>return 0</i> and betraying is <i>return 1</i>.<br>
            <h2>Examples for strategies</h2>
            <ul>
                <li>always betray - <i>return 1</i></li>
                <li>Non-nice tit-for-tat - will be <i>if self.first_turn: return 1; return self.get_last_choice("kevin")</i> (assuming the other player is kevin)</li>
            </ul>
        </p>
</div>

web/prisoner/game/templates/game/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'prisoner/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'prisoner/component.css' %}" />

<!-- The page header -->
<div id="headerwrapper">
    <div id="header">
        <h1>{{ title }}</h1>
    </div>
</div>

<!--  -->
<div id="menu">
    <div id="menu-buttons">
        <button class="btn btn-5 btn-5a icon-arrow-right" onclick="window.location.href='{% url 'game:first_prisoner' %}'">
            <span>Play</span>
        </button>
        <button class="btn btn-5 btn-5a icon-star-2" onclick="window.location.href='{% url 'game:help_page' %}'">
            <span>Help</span>
        </button>
        <button class="btn btn-5 btn-5a icon-cog" onclick="window.location.href='{% url 'admin:index' %}'">
            <span>Admin</span>
        </button>
    </div>
</div>

web/prisoner/game/templates/game/invalid_code.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'prisoner/style.css' %}" />

<div id="headerwrapper">
    <div id="header">
        <h1>Invalid code!</h1>
        <div id="logo"></div>
    </div>
</div>
<div id="results">
    <label>
        <span>Name : {{ name }}</span>
    </label>
    <label>
        <span>
            <p>
                Invalid code...
            </p>
            <textarea>
                {{ strategy_text }}
            </textarea>
        </span>
        <a href="{% url 'game:index' %}">Back to game</a>
    </label>
</div>

web/prisoner/game/templates/game/prisoner.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'prisoner/style.css' %}" />

<!-- The page header -->
<div id="headerwrapper">
    <div id="header">
        <h1>{{ title }}</h1>
        <div id="logo"></div>
    </div>
</div>

<!-- The game form itself  -->
<div id="game">
    <div id="game_form">
        {% with "game:"|add:dest_page as dest_page %}
        <form action="{% url dest_page %}" method="post" class="dark-matter">
        {% endwith %}
            {% csrf_token %}
                <h1>
                    Prisoner #{{ prisoner_number }}
                    <span>Please enter your prisoner's strategy in Python.</span>
                </h1>
                <p>
                    <label>
                        <span>Name</span>
                        <input id="name" type="text" name="name" placeholder="Prisoner #{{ prisoner_number }}" required autofocus="">
                    </label>
                    <label>
The strategy should be Python code, which always returns 1 or 0. <b>If you return 0, you cooperate (keep quiet). If you return 1, you betray (rat out).</b>
<br><br>
Make sure your Python is valid - 4 spaces are indentation, etc. The code should be a function body, e.g. without the <i>def func():</i> line. The def will be added later.
<br><br>
You have access to the following information:
                            <ul>
                                <li><i>self.first_turn</i> - boolean value. tells you if it's the first turn of the game.</li>
                                <li><i>self.get_last_choice(name)</i> - returns a number (0, 1). Enter the name of the a player to get his last choice.</li>
                                <li><i>self.{NAME}_choices</i> - Python list, holds all choices of {NAME}.</li>
                            </ul>
                    </label>
                    <label>
                        <span>Strategy</span>
                        <textarea id="strategy" name="strategy" placeholder="The prisoner's strategy..." required></textarea>
                    </label>
                </p>
                <label>
                    <span>&nbsp;</span>
                    <input type="submit" class="button" value="Send">
                </label>
        </form>
    </div>
</div>

web/prisoner/game/templates/game/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'prisoner/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'prisoner/results.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'prisoner/component.css' %}" />

<div id="headerwrapper">
    <div id="header">
        <h1>Results</h1>
        <div id="logo"></div>
    </div>
</div>
<div id="results">
    <div class="players">
        {% if not tie %}
        <div id="winner" class="player box effect1">
        {% else %}
        <div id="lefttie" class="player box effect1">
        {% endif %}
            <h1> {{ winner.name }} </h1>
            <h3>Years: {{ winner.years }}</h3>

            <input type="radio" id="show1" name="group1">
            <input type="radio" id="hide1" name="group1" checked>
            <label for="hide1" class="hide1"></label>
            <label for="show1" class="show1"></label>
            <span id="strategy1">
                <pre>{{ winner.strategy }}</pre>
            </span>

            <!--<div class="strategy">Hover to see strategy...<div class="showme"></div></div>-->
        </div>
        {% if not tie %}
        <div id="loser" class="player box effect1">
        {% else %}
        <div id="righttie" class="player box effect1">
        {% endif %}
            <h1> {{ loser.name }} </h1>
            <h3>Years: {{ loser.years }}</h3>

            <input type="radio" id="show2" name="group2" />
            <input type="radio" id="hide2" name="group2" checked />
            <label for="hide2" class="hide2"></label>
            <label for="show2" class="show2"></label>
            <span id="strategy2">
                <pre>{{ loser.strategy }}</pre>
            </span>
        </div>
        <br style="clear:both;" />

        <button class="btn btn-5 btn-5a icon-arrow-left" onclick="window.location.href='{% url 'game:index' %}'">
            <span>Back to main menu?</span>
        </button>
    </div>
</div>